#!/usr/bin/env node
"use strict";
/**
 * Build a Clubhouse run's context from the thread, as cheaply as it can be done
 * without losing an instruction.
 *
 * THE PLAN AND ITS EVIDENCE ARE IN docs/AUTOPILOT_CONTEXT.md. In short, a
 * 60-comment thread measures as: Claude's own replies 76% of the bytes, live
 * progress panels 19%, retry/failure notices 3%, and THE OWNER'S MESSAGES 2%.
 * So:
 *
 *   1. noise (progress panels, retry notices, failure notices, version stamps,
 *      footers) is DELETED — deterministic, free, ~22% gone before a token is
 *      spent;
 *   2. the owner's messages are NEVER compacted — 2% of the bytes and 100% of
 *      the instructions, including standing preferences stated once in passing;
 *   3. Claude's replies are compacted by HAIKU, once per comment, CACHED by
 *      comment id, so a reply is summarised exactly once in its life;
 *   4. the last N messages are verbatim regardless, because a run works out
 *      what is unanswered by looking back past its own last reply;
 *   5. nothing here may break a run — every failure falls back to a plain tail.
 *
 *   node compress-history.js --cache <file> < comments.json > context.txt
 *
 * stdin is the GitHub comments array (id, author, body). Env:
 *   ANTHROPIC_API_KEY   required to compact; without it, noise is still dropped
 *   GC_HISTORY_KEEP     verbatim messages to keep (default 10)
 *   GC_HISTORY_BUDGET   bytes below which nothing is compacted (default 12000)
 */

const fs = require("fs");

const KEEP = parseInt(process.env.GC_HISTORY_KEEP || "10", 10);
const BUDGET = parseInt(process.env.GC_HISTORY_BUDGET || "12000", 10);
const MODEL = "claude-haiku-4-5-20251001";
const cacheIdx = process.argv.indexOf("--cache");
const CACHE = cacheIdx > -1 ? process.argv[cacheIdx + 1] : null;

// NOISE. Machinery reporting on itself: a future run gains nothing from
// knowing that an earlier one retried, or which files its progress panel
// listed. Matched on the exact strings the workflow itself writes, so a real
// message can never be mistaken for one.
const NOISE = [
  /^\*\*Claude is working:\*\*/,
  /^\*\*Claude says:\*\*\s*\n+That run hit a snag/,
  /^\*\*Claude says:\*\*\s*\n+Something went wrong while handling that/,
  /^\*\*Claude says:\*\*\s*\n+I tried \d+ times and still could not/,
];
const STRIP = [
  /\n*\[v0\.\d+\]\s*$/,                                  // deploy version stamp
  /\n*---\n*_Generated by \[Claude Code\][^\n]*\n*/g,    // attribution footer
];

const isNoise = (b) => NOISE.some((re) => re.test(b.trim()));
const strip = (b) => STRIP.reduce((acc, re) => acc.replace(re, ""), b).trim();
const isClaude = (b) => /^\*\*Claude says:\*\*/.test(b.trim());

function readStdin() {
  return new Promise((res) => {
    let d = "";
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (c) => (d += c));
    process.stdin.on("end", () => res(d));
  });
}

function loadCache() {
  if (!CACHE) return {};
  try { return JSON.parse(fs.readFileSync(CACHE, "utf8")); } catch { return {}; }
}
function saveCache(c) {
  if (!CACHE) return;
  try { fs.writeFileSync(CACHE, JSON.stringify(c)); }
  catch (e) { console.error(`[compress] could not write cache: ${e.message}`); }
}

async function haiku(text) {
  const key = process.env.ANTHROPIC_API_KEY;
  if (!key) return null;
  const ctl = new AbortController();
  const timer = setTimeout(() => ctl.abort(), 45000);
  try {
    const res = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: { "content-type": "application/json", "x-api-key": key,
                 "anthropic-version": "2023-06-01" },
      signal: ctl.signal,
      body: JSON.stringify({
        model: MODEL,
        max_tokens: 220,
        messages: [{ role: "user", content:
          "This is one message an automated assistant posted to a game's chat thread, " +
          "reporting what it changed. Compress it to at most three short lines stating " +
          "only WHAT NOW EXISTS OR CHANGED in the game or its tooling, and anything it " +
          "said was still outstanding or broken. Drop all reasoning, diagnosis, " +
          "verification notes and apologies. No preamble.\n\n" + text }],
      }),
    });
    if (!res.ok) { console.error(`[compress] HTTP ${res.status}`); return null; }
    const d = await res.json();
    const t = (d.content || []).map((c) => c.text || "").join("").trim();
    return t || null;
  } catch (e) {
    console.error(`[compress] ${e.message}`);
    return null;
  } finally { clearTimeout(timer); }
}

(async () => {
  const raw = await readStdin();
  let comments;
  try {
    comments = JSON.parse(raw);
    if (!Array.isArray(comments)) throw new Error("not an array");
  } catch (e) {
    // Not JSON (an older caller, or gh failed): pass it through untouched
    // rather than dropping the thread on the floor.
    console.error(`[compress] input is not a comments array (${e.message}) — passing through`);
    process.stdout.write(raw.replace(/\n*$/, "\n"));
    return;
  }

  const before = raw.length;
  const kept = [];
  let dropped = 0;
  for (const c of comments) {
    const body = (c.body || "");
    if (!body.trim()) continue;
    if (isNoise(body)) { dropped++; continue; }
    kept.push({ id: String(c.id || ""), who: (c.author && c.author.login) || c.user?.login || "unknown",
                body: strip(body) });
  }

  const total = kept.reduce((n, c) => n + c.body.length, 0);
  const head = kept.length > KEEP ? kept.slice(0, kept.length - KEEP) : [];
  const tail = kept.slice(-KEEP);

  const cache = loadCache();
  let calls = 0, hits = 0;
  const lines = [];
  if (total > BUDGET && head.length) {
    for (const c of head) {
      // RULE 2: the owner's messages are never compacted. They are tiny and
      // they are the instructions — including preferences stated once, in
      // passing, that must hold forever.
      if (!isClaude(c.body)) { lines.push(c.body); continue; }
      if (cache[c.id]) { lines.push(cache[c.id]); hits++; continue; }
      const short = await haiku(c.body);
      if (short) { cache[c.id] = short; calls++; lines.push(short); }
      else lines.push(c.body.slice(0, 300) + (c.body.length > 300 ? " […]" : ""));
    }
    saveCache(cache);
  } else {
    for (const c of head) lines.push(c.body);
  }

  const out = [];
  if (lines.length) {
    out.push("=== EARLIER IN THIS THREAD ===");
    out.push("The owner's messages are verbatim. Claude's replies are compacted to");
    out.push("what changed. Anything the owner states is a STANDING instruction.");
    out.push("");
    out.push(lines.join("\n\n---\n\n"));
    out.push("");
  }
  out.push(`=== THE LAST ${tail.length} MESSAGES, VERBATIM ===`);
  out.push(tail.map((c) => c.body).join("\n\n---\n\n"));
  // ALWAYS end with a newline. Without one, the caller's
  //   { echo "thread<<EOF"; cat thread.txt; echo "EOF"; } >> $GITHUB_OUTPUT
  // puts the delimiter on the same line as the last message, GitHub reports
  // "Invalid value. Matching delimiter not found", and the step fails AFTER
  // all the work is done — the compressor logged a perfect run (86 comments,
  // 29 noise dropped, 76KB -> 14.8KB, 23 Haiku calls) and the job died on the
  // next line. The previous version got away with it because `gh` happened to
  // end its output with a newline.
  const result = out.join("\n").replace(/\n*$/, "\n");
  process.stdout.write(result);
  console.error(
    `[compress] ${comments.length} comments, ${dropped} noise dropped; ` +
    `${before}B -> ${result.length}B; haiku calls ${calls}, cache hits ${hits}`
  );
})();
